#!/usr/bin/env bash
#
# show-wg-keys.sh
#
# Prints the WireGuard server keypair generated by setup-wg-server.sh,
# regardless of whether it was generated on macOS (~/.wireguard-dev) or
# Linux (/etc/wireguard).
#
# Usage:
#   ./show-wg-keys.sh

set -euo pipefail

OS="$(uname -s)"

case "$OS" in
  Linux)
    CONF_DIR="/etc/wireguard"
    ;;
  Darwin)
    CONF_DIR="$HOME/.wireguard-dev"
    ;;
  *)
    echo "Unsupported OS: $OS" >&2
    exit 1
    ;;
esac

PRIV_FILE="${CONF_DIR}/server_private.key"
PUB_FILE="${CONF_DIR}/server_public.key"

if [[ ! -f "$PRIV_FILE" || ! -f "$PUB_FILE" ]]; then
  echo "No keys found in ${CONF_DIR}." >&2
  echo "Did you run setup-wg-server.sh on this machine yet?" >&2
  exit 1
fi

# Linux's key file is root-owned (0600) since setup-wg-server.sh runs as
# root there - reading it back also needs sudo. macOS's copy lives under
# the invoking user's home dir, so no sudo needed there.
read_key() {
  local file="$1"
  if [[ "$OS" == "Linux" && ! -r "$file" ]]; then
    sudo cat "$file"
  else
    cat "$file"
  fi
}

echo "==> Keys found in ${CONF_DIR}"
echo ""
echo "WG_SERVER_PRIVATE_KEY=$(read_key "$PRIV_FILE")"
echo "WG_SERVER_PUBLIC_KEY=$(read_key "$PUB_FILE")"
echo ""
echo "Treat the private key like any other secret - avoid pasting it"
echo "into chat logs, tickets, or shared docs. If it's ever been shared"
echo "somewhere it shouldn't, regenerate it by deleting ${CONF_DIR}/server_*.key"
echo "and re-running setup-wg-server.sh (this rotates the server identity,"
echo "so every router's peer config pointing at the old public key will"
echo "need to be re-provisioned)."